//FIRST lINE OF CODE IN JS
document.write("Hello World");
document.write("1000");

// Adding HTML tags in JS
document.write("</br></br>");
document.write("100 </br>");

document.write("<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio tempora id nemo optio eligendi voluptas.</p>");

//js variables: => 
//let,var and const

//VAR
// Can be redeclared - No ERROR on console
// Can be used before Declaration -- Undefined on console
// Global scope
var x = "Hellow World"
document.write(x)

//Its must either to use single quote or double quote but no the mix of both in case of string
x ="Wow!"
document.write(x,"</br>");

var first, second;
first =100;
document.write(first);

//let 
//Can not be redeclared
//can not be used before Declaration
//block level scope
let name = "Kiran";
// let name ="Atul"; -- Error on sonsole
name = "Atul"; // CAN be Modified the value


//const
//can not be modified
// can not be redeclared
const con = 100;
// con = 200; // Error on console 

/*===============DATA TYPES============== */

//Primitive: String Number Boolean
//Non Primitve : Array,object,null, undefined 

var st = "Kiran"; //String
st = 125; //Number
st = "125"; // String
st = true;// boolean

document.write("</br>",typeof(st),"</br>");
st ="Welcome"; 
document.write(typeof("</br>",st));
document.write("</br>",st);

var array= ["A","123",0.98];
document.write(array,"  ",typeof array)//A,123,0.98 Object

document.write(" ",typeof null)//null

document.write(" ",typeof undefined)//undefined

document.write(X);
var X =100;

console.log(X);
console.log(typeof X);//number

/*=============== Arithmetic Operator ============== */
 var a,b,c;
 a =10,b=10;
 c=a+b;
 console.log();
 console.log(c, typeof c)//20 number
 console.log(c-a, typeof c)//10 number
 console.log(c/a, typeof c/a)//2 number
 console.log(c%a, typeof c)//0 number
 console.log(c*a, typeof c)//200 number
 console.log(3**2)//9
//  console.log(3++)//ERROR
console.log(a++)//10
console.log(++a)//12

/*=============== Assignment Operators ============== */
console.log(a==b);//false
console.log(a=c,a);//20 20
console.log(a+=c);//40
console.log(a);//40
// console.log(2**=100);//ERROR 
var d =1;
 console.log(d**=100);//1
 d =2;
 console.log(d**=100);//1.2676506002282294e+30

/*=============== Console ============== */
console.time();

console.log("Looged on the console");

console.error("This is an Error generated by programmer with the console");

console.warn("this is an warning created by the user with the console")
console.warn("this is an warning created by the user with the console",typeof null,10+100,array['A','B'])// Whats diss...?

console.log([1,2,3,4,5]);

console.table([1,2,3,4,5]);

console.timeEnd();

console.clear();

//DOM on console

document.getElementById("header");

document.getElementById("header").innerHTML; 

document.getElementById("header").innerText;
/*
"Title
WorkForce" 
*/ 
/*===============Comparision operators ============== */


// === vs == in first the data type must be same to get the true result and in second only value is checked irrespective of the data type


var x =10;
var y ="10"
// let x = "10"; // Erro as x already defined
let p = 10; 
let q ="10"

console.log(x==p)//true
console.log(x==y)//true
console.log(p==y)//true

console.log(x===p)//true
console.log(x===y)//false
console.log(p===y)//false

console.log(null===null)//true
console.log(undefined===undefined)//true
console.log(undefined===null)//false


/*=============== IF else in JS ============== */

if (x===y){ //false condition
    console.log("Style changed");
}
else{
    console.log("No Style changed");
}

var age =23;
if(age<=18 & age>=14){
    console.log("You are a student!")  
}
else if(age>18){
    console.log("You are a senior student!")  
}
else{
    console.log("Tum abhi bachhe ho!")  
}
// You are a senior student!

 age =18;
if(age<=18 & age>=14){
    console.log("You are a student!")  
}
else if(age>=18){ // even age is 18 and two consitions are satisfiying then also only first condition will get execute
    console.log("You are a senior student!")  
}
else{
    console.log("Tum abhi bachhe ho!")  
}


if(!(8>9)){
    console.log("true condition!")  
}

// ------------------------------

// DOM Manipulation with if else
var uname = "Kiran"
if(uname=="Kiran"){
    document.getElementById("header").innerHTML = "Welcome back Mr." + uname;
}

/*============= Switch Case ====================*/

// age validation with switch case

var age =25;

switch (true) {
    case (age<=18):
    document.getElementById("header").innerHTML ="Mr. " + uname + "is not eligible for this event";
        break;
    case(age<=25):
    document.getElementById("header").innerHTML ="Mr. " + uname + " is eligible for this event";
    default:
        break;
}
/*---------------- Alerts in JS ----------------------*/

var a =100;
var b =25;

if(a>b){
    // alert("the greater value is of a and its " + a);
    // alert(a+b);
    // alert("the value of b is " + b);
}

/*---------------------- CONFIRM BOX IN JS ------------*/

// CONFIRM() ask for two values OK(true) and Cancel(false) and we can store these values in the variables

// let res = confirm("How was  your experience?");
// alert(res)
var res;
if(res){
    alert("We glad you liked it!");
}
else{
    // alert("Thanks for your feedback!");
}

/*--------------- PROMPT BOX ------------------------*/

// with this we can take any value from user and use it in our program

// var res = prompt("Rate us out of 5");
document.write("</br> </br> </br>",res);


/*====================== JS FUNCTIONS ==================*/

// FUNCTION Defined
function hello(){
    document.write("</br>")
    document.write("Hey! its my FIRST function is JS");
}
hello();
hello();
hello();
hello();

// paramterised function

function demo(a,b){
    if(typeof a == "number" && typeof b == "number"){
        alert("Both are the numbers")
    }
    else if(typeof a === "number" && typeof b !== "number")
    {
        alert("Only a is the numbers")   
    }
    else if(typeof a !== "number" && typeof b == "number"){
        alert("Only b is the numbers")   
    }
    else(
        alert("Neither are the numbers")   
    )
}

// demo();
// demo(12,13);

//NOTE : There is no issue even if we pass more or less arguments than defined in the function, If given less arguments then parameter who didnt got any value will be "undefined" 

